# Topic Modeling

## Topic Modeling - Attempt #1 (All Text)

In [243]:
# Read in the document-term matrix
import pandas as pd

data_clean = pd.read_csv("lyrics_clean.csv",index_col=0)
#data_clean=data.loc[['ABBA','Janis_Joplin','Queen','Pink_Floyd'],:]

## LSA

In [244]:
# Let's update our document-term matrix with the new list of stop words
from sklearn.feature_extraction import text 
from sklearn.feature_extraction.text import CountVectorizer

# Add new stop words,
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

stop_words2=[]
for w in stop_words:
    stop_words2.append(w)

stop_words2.extend(['girl','bird','la','li','ooh','let','number','jude','whoa','da','ta'])

cv = CountVectorizer(min_df=.2, max_df=.8,stop_words=stop_words2)
data_cv = cv.fit_transform(data_clean.lyrics)

In [245]:
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_dtm.index = data_clean.index
data_dtm

,aah,abandon,able,abuse,accept,ache,act,action,advice,affair,...,wreck,writ,write,ya,yawn,yellow,yesterday,yo,york,youth
ABBA,0,0,1,0,0,0,0,1,0,4,...,0,0,1,1,1,0,0,1,0,0
David_Bowie,0,0,0,0,0,1,1,1,0,1,...,2,2,5,4,1,0,1,0,2,1
Janis_Joplin,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Michael_Jackson,1,1,1,5,0,1,2,0,1,0,...,0,0,0,3,1,1,2,1,0,0
Queen,7,1,0,1,0,3,1,1,0,0,...,0,0,4,0,0,1,1,0,0,3
Rolling_Stones,0,0,0,1,0,1,0,0,0,1,...,0,0,0,2,0,1,2,0,1,1
The_Clash,0,0,0,0,0,0,0,0,1,0,...,0,1,1,55,0,1,0,14,3,3
Bob_Dylan,0,1,1,0,2,3,3,0,1,1,...,1,0,6,33,0,1,3,0,1,0
Elton_John,0,0,0,1,0,3,2,3,0,2,...,1,0,4,8,0,8,0,0,5,0
Led_Zeppeling,0,0,0,2,0,1,0,0,0,0,...,0,1,1,1,0,1,2,0,0,1
Pink_Floyd,0,0,1,1,1,0,0,1,0,0,...,0,0,1,7,0,0,1,0,0,0
Ramones,2,0,0,0,4,0,0,2,0,0,...,0,0,0,0,0,0,1,0,0,0
The_Beatles,1,0,1,0,0,0,1,0,0,0,...,0,0,2,1,0,28,12,0,0,0
The_Doors,0,0,0,0,0,0,0,0,0,0,...,0,0,1,10,0,0,0,0,0,0

In [246]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(min_df=.4, max_df=.8,stop_words=stop_words2)
tfidf = vectorizer.fit_transform(data_clean.lyrics)
len(vectorizer.get_feature_names())

542

In [247]:
data_tfidf = pd.DataFrame(tfidf.toarray(), columns=vectorizer.get_feature_names())
data_tfidf.index = data_clean.index
data_tfidf

,abuse,ache,act,action,afraid,age,ago,agree,ah,ahead,...,wish,wonder,woo,worry,worth,wouldnt,write,ya,yellow,yesterday
ABBA,0.000000,0.000000,0.000000,0.013700,0.013700,0.011746,0.011746,0.027400,0.038038,0.000000,...,0.066566,0.095095,0.025324,0.020372,0.027400,0.023492,0.010186,0.009509,0.000000,0.000000
David_Bowie,0.000000,0.009080,0.009824,0.009824,0.392977,0.016847,0.016847,0.000000,0.225039,0.009080,...,0.020458,0.061374,0.045400,0.000000,0.000000,0.016847,0.036522,0.027277,0.000000,0.007304
Janis_Joplin,0.000000,0.000000,0.000000,0.000000,0.000000,0.023960,0.000000,0.000000,0.193974,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020777
Michael_Jackson,0.042592,0.007873,0.017037,0.000000,0.000000,0.007304,0.000000,0.008518,0.295641,0.000000,...,0.059128,0.017738,0.125966,0.012667,0.051110,0.131463,0.000000,0.017738,0.007304,0.012667
Queen,0.012127,0.033625,0.012127,0.012127,0.000000,0.010398,0.010398,0.000000,0.370382,0.011208,...,0.033671,0.008418,0.100874,0.009017,0.000000,0.000000,0.036066,0.000000,0.010398,0.009017
Rolling_Stones,0.013531,0.012505,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.291154,0.012505,...,0.000000,0.000000,0.137560,0.020120,0.000000,0.000000,0.000000,0.018784,0.011601,0.020120
The_Clash,0.000000,0.000000,0.000000,0.000000,0.000000,0.033750,0.000000,0.019682,0.000000,0.009095,...,0.020492,0.006831,0.000000,0.014633,0.000000,0.008437,0.007317,0.375693,0.008437,0.000000
Bob_Dylan,0.000000,0.027848,0.030131,0.000000,0.020087,0.034445,0.017223,0.020087,0.069716,0.009283,...,0.076687,0.083659,0.000000,0.007468,0.030131,0.060279,0.044805,0.230062,0.008611,0.022403
Elton_John,0.010968,0.030411,0.021937,0.032905,0.000000,0.000000,0.028212,0.010968,0.213173,0.000000,...,0.007613,0.007613,0.000000,0.008155,0.021937,0.000000,0.032620,0.060907,0.075232,0.000000
Led_Zeppeling,0.026360,0.012181,0.000000,0.000000,0.000000,0.022601,0.067802,0.000000,0.548915,0.000000,...,0.018297,0.118932,0.000000,0.039198,0.000000,0.022601,0.009799,0.009149,0.011300,0.019599
Pink_Floyd,0.021126,0.000000,0.000000,0.021126,0.021126,0.000000,0.000000,0.000000,0.043993,0.000000,...,0.058657,0.102649,0.000000,0.000000,0.021126,0.000000,0.015707,0.102649,0.000000,0.015707
Ramones,0.000000,0.000000,0.000000,0.033729,0.000000,0.000000,0.000000,0.000000,0.000000,0.015587,...,0.011706,0.046824,0.000000,0.025078,0.000000,0.014459,0.000000,0.000000,0.000000,0.012539
The_Beatles,0.000000,0.000000,0.016250,0.000000,0.016250,0.000000,0.041798,0.032501,0.078959,0.045057,...,0.011280,0.000000,0.075095,0.012082,0.016250,0.041798,0.024164,0.011280,0.390119,0.144987
The_Doors,0.000000,0.000000,0.000000,0.000000,0.043155,0.000000,0.024667,0.000000,0.000000,0.000000,...,0.000000,0.039940,0.013295,0.000000,0.000000,0.000000,0.010695,0.099849,0.000000,0.000000

In [248]:
from sklearn.decomposition import TruncatedSVD

# SVD represent documents and terms in vectors 
svd_model = TruncatedSVD(n_components=5)

svd_model.fit(data_tfidf)

print(svd_model.components_.shape)
print(svd_model.singular_values_)

(5, 542)
[2.12038642 1.05417987 0.98781762 0.94785088 0.91290844]

In [249]:
terms = vectorizer.get_feature_names()

for i, comp in enumerate(svd_model.components_):
    terms_comp = zip(terms, comp)
    sorted_terms = sorted(terms_comp, key= lambda x:x[1], reverse=True)[:7]
    print("Topic "+str(i)+": ")
    for t in sorted_terms:
        print("%.2f*%s "% (t[1], t[0]) ,end='')
    print("")

Topic 0:
0.31*ah 0.22*babe 0.13*roll 0.13*ya 0.11*black 0.11*kiss 0.11*dead
Topic 1:
0.46*babe 0.38*ah 0.16*anybody 0.14*dear 0.13*piece 0.13*bit 0.12*bout
Topic 2:
0.30*kiss 0.26*gim 0.20*ah 0.16*wasnt 0.14*midnight 0.11*woo 0.09*monkey
Topic 3:
0.32*kiss 0.26*gim 0.23*family 0.19*babe 0.19*wasnt 0.16*beach 0.14*roll
Topic 4:
0.37*family 0.27*ah 0.21*bitch 0.20*beach 0.14*fame 0.14*saturday 0.12*theyll

## LDA

In [250]:
# We are going to create a document-term matrix using CountVectorizer, and exclude common English stop words
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words=stop_words2,min_df=.2, max_df=.8)
data_cv = cv.fit_transform(data_clean.lyrics)
data = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data.index = data_clean.index
data

,aah,abandon,able,abuse,accept,ache,act,action,advice,affair,...,wreck,writ,write,ya,yawn,yellow,yesterday,yo,york,youth
ABBA,0,0,1,0,0,0,0,1,0,4,...,0,0,1,1,1,0,0,1,0,0
David_Bowie,0,0,0,0,0,1,1,1,0,1,...,2,2,5,4,1,0,1,0,2,1
Janis_Joplin,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Michael_Jackson,1,1,1,5,0,1,2,0,1,0,...,0,0,0,3,1,1,2,1,0,0
Queen,7,1,0,1,0,3,1,1,0,0,...,0,0,4,0,0,1,1,0,0,3
Rolling_Stones,0,0,0,1,0,1,0,0,0,1,...,0,0,0,2,0,1,2,0,1,1
The_Clash,0,0,0,0,0,0,0,0,1,0,...,0,1,1,55,0,1,0,14,3,3
Bob_Dylan,0,1,1,0,2,3,3,0,1,1,...,1,0,6,33,0,1,3,0,1,0
Elton_John,0,0,0,1,0,3,2,3,0,2,...,1,0,4,8,0,8,0,0,5,0
Led_Zeppeling,0,0,0,2,0,1,0,0,0,0,...,0,1,1,1,0,1,2,0,0,1
Pink_Floyd,0,0,1,1,1,0,0,1,0,0,...,0,0,1,7,0,0,1,0,0,0
Ramones,2,0,0,0,4,0,0,2,0,0,...,0,0,0,0,0,0,1,0,0,0
The_Beatles,1,0,1,0,0,0,1,0,0,0,...,0,0,2,1,0,28,12,0,0,0
The_Doors,0,0,0,0,0,0,0,0,0,0,...,0,0,1,10,0,0,0,0,0,0

In [251]:
from gensim import matutils, models
import scipy.sparse

In [252]:
tdm = data.transpose()
tdm.head()

,ABBA,David_Bowie,Janis_Joplin,Michael_Jackson,Queen,Rolling_Stones,The_Clash,Bob_Dylan,Elton_John,Led_Zeppeling,Pink_Floyd,Ramones,The_Beatles,The_Doors
aah,0,0,1,1,7,0,0,0,0,0,0,2,1,0
abandon,0,0,0,1,1,0,0,1,0,0,0,0,0,0
able,1,0,0,1,0,0,0,1,0,0,1,0,1,0
abuse,0,0,0,5,1,1,0,0,1,2,1,0,0,0
accept,0,0,0,0,0,0,0,2,0,0,1,4,0,0

In [253]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [254]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

In [255]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2)
lda.print_topics()

[(0,
  '0.010*"ah" + 0.010*"babe" + 0.006*"ya" + 0.006*"roll" + 0.004*"okay" + 0.004*"law" + 0.004*"til" + 0.004*"lady" + 0.004*"kiss" + 0.004*"city"'),
 (1,
  '0.014*"ah" + 0.005*"kiss" + 0.005*"black" + 0.005*"roll" + 0.005*"dead" + 0.004*"ya" + 0.004*"white" + 0.004*"lady" + 0.004*"radio" + 0.004*"gun"')]

In [256]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3)
lda.print_topics()

[(0,
  '0.016*"ah" + 0.005*"ya" + 0.005*"kiss" + 0.005*"babe" + 0.005*"lady" + 0.004*"dead" + 0.004*"mama" + 0.004*"gun" + 0.004*"lover" + 0.004*"black"'),
 (1,
  '0.010*"babe" + 0.008*"ah" + 0.007*"roll" + 0.006*"ya" + 0.004*"dead" + 0.004*"black" + 0.004*"theyll" + 0.004*"white" + 0.004*"law" + 0.004*"family"'),
 (2,
  '0.010*"ah" + 0.006*"babe" + 0.006*"roll" + 0.005*"okay" + 0.005*"ya" + 0.004*"city" + 0.004*"dead" + 0.004*"american" + 0.004*"blood" + 0.004*"til"')]

In [257]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4)
lda.print_topics()

[(0,
  '0.010*"ah" + 0.005*"black" + 0.005*"roll" + 0.005*"babe" + 0.005*"radio" + 0.005*"dead" + 0.004*"shatter" + 0.004*"kiss" + 0.004*"lady" + 0.004*"ya"'),
 (1,
  '0.010*"ah" + 0.007*"roll" + 0.006*"babe" + 0.005*"ya" + 0.005*"fame" + 0.005*"american" + 0.005*"white" + 0.005*"city" + 0.004*"kiss" + 0.004*"law"'),
 (2,
  '0.018*"ah" + 0.006*"babe" + 0.005*"ya" + 0.005*"lady" + 0.005*"dead" + 0.005*"roll" + 0.005*"forever" + 0.004*"black" + 0.004*"mama" + 0.004*"lover"'),
 (3,
  '0.010*"babe" + 0.010*"ah" + 0.006*"ya" + 0.005*"kiss" + 0.005*"lover" + 0.004*"roll" + 0.004*"dead" + 0.004*"stone" + 0.004*"black" + 0.004*"til"')]

## Topic Modeling - Attempt #2 (Nouns Only)

In [226]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [227]:
# Read in the cleaned data, before the CountVectorizer step
import pandas as pd

data_clean = pd.read_csv("lyrics_clean.csv",index_col=0)
data_clean

                                                            lyrics
ABBA             ive love thought would manage hit ceiling stil...
David_Bowie      small jean genie snuck city strung laser slash...
Janis_Joplin     oh come come come come didnt make feel like ma...
Michael_Jackson  butt mine gon na tell right show face broad da...
Queen            dim light sing song full sad thing tango two s...
Rolling_Stones   drag get old kid different today hear every mo...
The_Clash        stay around dont play around old town seem lik...
Bob_Dylan        go away window leave choose speed im one want ...
Elton_John       hear distance sense far away old rudolph reind...
Led_Zeppeling    hey thats right ask sweet mama let kid say mig...
Pink_Floyd       distance ribbon black stretch point turn back ...
Ramones          im lie bed night dont want grow nothing ever s...
The_Beatles      jojo man think loner know couldnt last jojo le...
The_Doors        lion street roam dog heat rabid foam beast cag...

In [228]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns = pd.DataFrame(data_clean.lyrics.apply(nouns))
data_nouns

                                                            lyrics
ABBA             love thought ceiling feeling dont think make d...
David_Bowie      jean city strung laser slash eat razor pull wa...
Janis_Joplin     didnt feel man yeah everything woman honey tim...
Michael_Jackson  butt mine gon show face im tell gon mind shoot...
Queen            dim light thing tango serenade heart valentino...
Rolling_Stones   drag kid today mother need something today she...
The_Clash        stay play town lotta people tonight lotta peop...
Bob_Dylan        window speed babe im need youre someone defend...
Elton_John       distance sense rudolph reindeer santa head eas...
Led_Zeppeling    hey thats mama kid keep hid baby see im rider ...
Pink_Floyd       distance ribbon stretch point flight fancy win...
Ramones          lie night dont grow nothing dont grow move wor...
The_Beatles      jojo man couldnt jojo home tucson california g...
The_Doors        lion street roam dog heat rabid foam beast hea...

In [229]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words, min_df=.1, max_df=.9)
data_cvn = cvn.fit_transform(data_nouns.lyrics)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

,aaaah,aah,abuse,ace,ache,act,action,actor,advertising,advice,...,yawn,yell,yellow,yes,yesterday,yo,york,youd,youll,youth
ABBA,0,0,0,1,0,0,1,0,0,0,...,0,0,0,7,0,1,0,0,4,0
David_Bowie,0,0,0,0,1,1,1,1,0,0,...,1,1,0,1,1,0,2,0,2,0
Janis_Joplin,0,0,0,0,0,0,0,0,0,0,...,0,0,0,4,1,0,0,0,0,0
Michael_Jackson,2,1,5,0,1,1,0,0,0,1,...,1,0,0,2,2,0,0,1,13,0
Queen,0,4,0,0,2,1,1,0,0,0,...,0,0,1,9,1,0,0,1,3,3
Rolling_Stones,0,0,0,0,1,0,0,0,0,0,...,0,0,1,10,2,0,1,1,1,1
The_Clash,0,0,0,0,0,0,0,0,2,1,...,0,0,0,4,0,12,1,0,4,3
Bob_Dylan,0,0,0,1,3,1,0,0,1,1,...,0,0,0,9,3,0,1,4,5,0
Elton_John,0,0,1,0,3,2,3,0,0,0,...,0,0,0,0,0,0,5,1,7,0
Led_Zeppeling,0,0,2,0,1,0,0,0,0,0,...,0,0,0,5,2,0,0,0,0,0
Pink_Floyd,0,0,0,0,0,0,1,0,0,0,...,0,1,0,3,1,0,0,1,9,0
Ramones,0,1,0,0,0,0,2,0,0,0,...,0,0,0,0,1,0,0,0,2,0
The_Beatles,4,1,0,0,0,0,0,0,0,0,...,0,0,0,5,12,0,0,0,1,0
The_Doors,0,0,0,0,0,0,0,2,0,0,...,0,0,0,2,0,0,0,1,3,0

In [230]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [231]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.024*"rock" + 0.019*"bird" + 0.019*"cause" + 0.017*"aint" + 0.014*"dance" + 0.014*"wan" + 0.012*"tonight" + 0.010*"care" + 0.010*"family" + 0.009*"stop"'),
 (1,
  '0.009*"aint" + 0.008*"ah" + 0.007*"babe" + 0.007*"number" + 0.007*"ooh" + 0.007*"cause" + 0.007*"rock" + 0.006*"honey" + 0.005*"somebody" + 0.005*"child"')]

In [232]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.014*"number" + 0.011*"aint" + 0.010*"rock" + 0.008*"law" + 0.007*"ya" + 0.007*"fame" + 0.006*"cause" + 0.006*"blow" + 0.006*"gun" + 0.006*"city"'),
 (1,
  '0.026*"rock" + 0.026*"bird" + 0.016*"dance" + 0.016*"tonight" + 0.014*"wan" + 0.010*"care" + 0.010*"family" + 0.010*"cause" + 0.009*"bitch" + 0.005*"freedom"'),
 (2,
  '0.015*"aint" + 0.015*"ah" + 0.013*"cause" + 0.013*"ooh" + 0.010*"babe" + 0.009*"honey" + 0.008*"stop" + 0.008*"lord" + 0.007*"somebody" + 0.007*"change"')]

In [233]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn)
ldan.print_topics()

[(0,
  '0.009*"rock" + 0.009*"cause" + 0.007*"aint" + 0.007*"ah" + 0.007*"honey" + 0.006*"wan" + 0.005*"place" + 0.005*"babe" + 0.005*"number" + 0.005*"dance"'),
 (1,
  '0.015*"rock" + 0.009*"aint" + 0.009*"dance" + 0.008*"bird" + 0.008*"ah" + 0.008*"ooh" + 0.008*"cause" + 0.007*"tonight" + 0.007*"roll" + 0.007*"babe"'),
 (2,
  '0.014*"aint" + 0.011*"cause" + 0.008*"ah" + 0.007*"rock" + 0.007*"number" + 0.007*"ooh" + 0.006*"dance" + 0.005*"place" + 0.005*"somebody" + 0.005*"change"'),
 (3,
  '0.015*"rock" + 0.012*"aint" + 0.012*"cause" + 0.009*"bird" + 0.009*"ah" + 0.008*"ooh" + 0.008*"dance" + 0.008*"number" + 0.008*"wan" + 0.007*"babe"')]

## Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [234]:
# Let's create a function to pull out nouns from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [235]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns_adj = pd.DataFrame(data_clean.lyrics.apply(nouns_adj))
data_nouns_adj

                                                            lyrics
ABBA             ive love thought ceiling strange old feeling d...
David_Bowie      small jean genie snuck city strung laser slash...
Janis_Joplin     come didnt feel man yeah everything woman hone...
Michael_Jackson  butt mine gon show face broad daylight im tell...
Queen            dim light song full sad thing tango serenade h...
Rolling_Stones   drag old kid different today mother mother nee...
The_Clash        stay dont play old town travel lotta people su...
Bob_Dylan        window choose speed babe im need youre someone...
Elton_John       hear distance sense old rudolph reindeer santa...
Led_Zeppeling    hey thats sweet mama kid dont keep hid baby da...
Pink_Floyd       distance ribbon black stretch point flight fan...
Ramones          im lie night dont grow nothing right dont grow...
The_Beatles      jojo man loner couldnt last jojo home tucson c...
The_Doors        lion street roam dog heat rabid foam beast cag...

In [236]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words2, min_df=.1, max_df=.7)
data_cvna = cvna.fit_transform(data_nouns_adj.lyrics)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aaaah,aah,abandon,able,abraham,abuse,accept,ace,ache,act,...,writ,write,writer,yawn,yearn,yell,yellow,yo,york,youth
ABBA,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
David_Bowie,0,0,0,0,0,0,0,0,1,1,...,2,5,0,1,0,1,0,0,2,0
Janis_Joplin,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Michael_Jackson,3,1,1,1,1,5,0,0,1,2,...,0,0,0,1,1,0,0,1,0,0
Queen,0,5,1,0,0,0,0,0,2,1,...,0,4,0,0,0,0,1,0,0,3
Rolling_Stones,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,1
The_Clash,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,12,3,3
Bob_Dylan,0,0,0,1,1,0,2,1,3,2,...,0,4,1,0,0,0,1,0,1,0
Elton_John,0,0,0,0,0,1,0,0,3,2,...,0,1,0,0,0,0,8,0,5,0
Led_Zeppeling,0,0,0,0,0,2,0,0,1,0,...,1,0,0,0,1,0,1,0,0,0
Pink_Floyd,0,0,0,1,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
Ramones,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The_Beatles,5,1,0,1,0,0,0,0,0,0,...,0,2,0,0,0,0,28,0,0,0
The_Doors,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [237]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [238]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.007*"law" + 0.006*"radio" + 0.006*"til" + 0.006*"okay" + 0.005*"family" + 0.005*"white" + 0.005*"shoot" + 0.005*"theyll" + 0.004*"force" + 0.004*"rhythm"'),
 (1,
  '0.006*"fame" + 0.006*"american" + 0.005*"afraid" + 0.005*"gold" + 0.005*"bitch" + 0.005*"shatter" + 0.004*"modern" + 0.004*"gim" + 0.004*"wild" + 0.004*"diamond"')]

In [239]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna)
ldana.print_topics()

[(0,
  '0.005*"radio" + 0.004*"family" + 0.004*"theyll" + 0.004*"white" + 0.004*"law" + 0.004*"shoot" + 0.003*"bitch" + 0.003*"saturday" + 0.003*"kiss" + 0.003*"fame"'),
 (1,
  '0.005*"law" + 0.004*"white" + 0.004*"til" + 0.004*"okay" + 0.004*"shoot" + 0.004*"kiss" + 0.004*"diamond" + 0.004*"force" + 0.003*"shatter" + 0.003*"gim"'),
 (2,
  '0.005*"fame" + 0.005*"til" + 0.004*"american" + 0.004*"white" + 0.004*"okay" + 0.004*"afraid" + 0.004*"family" + 0.003*"radio" + 0.003*"gold" + 0.003*"annie"')]

In [240]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna)
ldana.print_topics()

[(0,
  '0.005*"family" + 0.004*"radio" + 0.004*"law" + 0.004*"fame" + 0.004*"shoot" + 0.003*"diamond" + 0.003*"theyll" + 0.003*"wonder" + 0.003*"white" + 0.003*"gim"'),
 (1,
  '0.004*"family" + 0.004*"shatter" + 0.004*"fame" + 0.003*"white" + 0.003*"law" + 0.003*"theyll" + 0.003*"bitch" + 0.003*"gim" + 0.003*"til" + 0.003*"kiss"'),
 (2,
  '0.006*"white" + 0.005*"okay" + 0.005*"til" + 0.004*"annie" + 0.004*"american" + 0.004*"law" + 0.004*"ha" + 0.004*"force" + 0.004*"fame" + 0.004*"cmon"'),
 (3,
  '0.004*"radio" + 0.004*"til" + 0.004*"white" + 0.004*"anybody" + 0.003*"wonder" + 0.003*"shoot" + 0.003*"kiss" + 0.003*"law" + 0.003*"american" + 0.003*"diamond"')]

## Identify Topics in Each Document

In [241]:
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna)
ldana.print_topics()

[(0,
  '0.005*"radio" + 0.005*"white" + 0.004*"shatter" + 0.004*"til" + 0.004*"okay" + 0.004*"family" + 0.003*"theyll" + 0.003*"kiss" + 0.003*"rhythm" + 0.003*"key"'),
 (1,
  '0.005*"shoot" + 0.004*"family" + 0.004*"fame" + 0.004*"law" + 0.004*"american" + 0.004*"white" + 0.004*"radio" + 0.003*"til" + 0.003*"diamond" + 0.003*"afraid"'),
 (2,
  '0.005*"family" + 0.005*"fame" + 0.004*"white" + 0.004*"diamond" + 0.004*"american" + 0.003*"theyll" + 0.003*"radio" + 0.003*"gold" + 0.003*"shoot" + 0.003*"bitch"'),
 (3,
  '0.006*"law" + 0.005*"til" + 0.004*"white" + 0.004*"okay" + 0.004*"wonder" + 0.003*"radio" + 0.003*"kiss" + 0.003*"ha" + 0.003*"gim" + 0.003*"wasnt"')]

In [242]:
corpus_transformed = ldana[corpusna]
for i,j in enumerate(list(corpus_transformed)):
    print(data_dtmna.index[i],j)

ABBA [(3, 0.99819946)]
David_Bowie [(2, 0.97788954), (3, 0.017636403)]
Janis_Joplin [(2, 0.9959925)]
Michael_Jackson [(0, 0.5059158), (3, 0.49378982)]
Queen [(0, 0.7803077), (3, 0.21345572)]
Rolling_Stones [(0, 0.9993867)]
The_Clash [(3, 0.9960987)]
Bob_Dylan [(0, 0.9996827)]
Elton_John [(2, 0.45745027), (3, 0.5421708)]
Led_Zeppeling [(3, 0.99920285)]
Pink_Floyd [(3, 0.9948399)]
Ramones [(2, 0.9904355)]
The_Beatles [(1, 0.96186715), (2, 0.02867573)]
The_Doors [(0, 0.99920666)]